# Generated by Django 3.2.9 on 2021-11-08 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField(verbose_name=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='app.profile')),
                ('tags', models.ManyToManyField(related_name='questions', to='app.Tag')),
                ('users_like', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions', to='app.like')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name=500)),
                ('checked', models.BooleanField(blank=True, null=True)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.question')),
                ('users_like', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='app.like')),
            ],
        ),
    ]
