# Generated by Django 3.2.9 on 2021-11-09 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='q',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name=500)),
                ('checked', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FilePathField(blank=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='q',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answer', to='app.profile'),
        ),
        migrations.AddField(
            model_name='q',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.question'),
        ),
        migrations.AddField(
            model_name='q',
            name='users_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='answer', to='app.like'),
        ),
    ]
