# Generated by Django 3.2.9 on 2021-11-09 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211109_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='q',
            new_name='Answer',
        ),
    ]
