# Generated by Django 3.2.9 on 2021-11-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211109_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='question',
            name='profile',
        ),
    ]
