# Generated by Django 3.2.9 on 2021-11-10 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20211109_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='users_like',
        ),
        migrations.RemoveField(
            model_name='question',
            name='users_like',
        ),
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_answer', to='app.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.profile'),
            preserve_default=False,
        ),
    ]
