# Generated by Django 3.2.9 on 2021-11-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211110_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='likeanswer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='likequestion',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_id',
            new_name='user',
        ),
    ]
