# Generated by Django 3.2.9 on 2021-11-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
