# Generated by Django 3.2.9 on 2021-11-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name=1000),
        ),
    ]
