# Generated by Django 3.2.9 on 2021-11-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='dislike_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
    ]
