# Generated by Django 3.2.9 on 2021-11-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_question_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='dislike_counter',
            new_name='dislike',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='like_counter',
            new_name='like',
        ),
    ]
