# Generated by Django 3.2.9 on 2021-11-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislike_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='like_counter',
            field=models.IntegerField(default=0),
        ),
    ]
