# Generated by Django 3.2.9 on 2021-11-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20211111_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
