# Generated by Django 3.2.9 on 2021-12-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likeanswer',
            constraint=models.UniqueConstraint(fields=('user', 'answer'), name='unique_user_answer'),
        ),
        migrations.AddConstraint(
            model_name='likequestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question'),
        ),
    ]
