# Generated by Django 3.2.9 on 2021-12-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20211206_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/img/Anon.jpg', null=True, upload_to='static/img'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
