# Generated by Django 3.2.9 on 2021-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20211207_1552'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='likeanswer',
            name='unique_user_answer',
        ),
        migrations.RemoveConstraint(
            model_name='likequestion',
            name='unique_user_question',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/img/Anon.jpg', null=True, upload_to='img'),
        ),
        migrations.AlterUniqueTogether(
            name='likeanswer',
            unique_together={('user', 'answer', 'check')},
        ),
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together={('user', 'question', 'check')},
        ),
    ]
