# Generated by Django 3.2.9 on 2021-12-27 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20211226_2110'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likequestion',
            unique_together=set(),
        ),
    ]
